---
- name: Install Apache and upload web page
  hosts: all
  become: yes
  
  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:

  - name: Install Apache
    yum: name=httpd state=latest

  - name: Copy web page to server
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache
    
  - name: Start web server
    service: name=httpd state=started enabled=yes
    
    
  hendlers:
  - name: Restart Apache
    service: name=httpd state=restarted  